name: Build ZMK firmware
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "config/*.conf"
      - "config/*.keymap"
      - "config/*.yml"
      - "snippets/rgb-config/*.conf"
      - "snippets/rgb-config/*.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
